# Generated by Django 3.2.4 on 2021-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
