# Generated by Django 3.2.4 on 2021-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_review_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
