# Generated by Django 3.2.4 on 2021-09-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='static/images/',
            ),
        ),
    ]
